### ISSUE TITLE
Camera stuck / softlock after story H end if no topic was gained

### ISSUE THREAD

**Issue by ManlyMarco** [IllusionMods/KKS_VR#10]

**Comment by Nerofaust** [comment]
Hello, yesterday I carried out several tests to try to identify the source of the problem of the error related to the soft lock after a story H.
I found that the stats display scene after story H end is handled in this function of the [GameFixes.cs](https://github.com/IllusionMods/KKS_VR/blob/2e780ad5e430ac214954d15318ab4c2c7d3c96bb/MainGameVR/Fixes/GameFixes.cs#L106) file.
If I comment it the game freeze and if I modify it the vr mode does not start.
ManlyMarco, I've never done C# before, do you know how to trigger the event when a topic is gained (or then just display a message, that would be a start) or else where in the code is it handled?
Thank you for your mod, it's amazing.

**Comment by momspaghetti123** [comment]
Is this related to #17?

**Comment by ManlyMarco** [comment]
Yes, this was fixed.
