### ISSUE TITLE
Look into porting/integrating ChuuuVR or similar

### ISSUE THREAD

**Issue by ManlyMarco** [IllusionMods/KKS_VR#28]
https://github.com/Sauceke/ChuuuVR/blob/master/ChuuuVR/KissController.cs

**Comment by Sauceke** [comment]
Happy to look into this; that plugin is in need of some serious doing-over.

**Comment by ManlyMarco** [comment]
That would be greatly appreciated. I was thinking about a dumbed down KKS_VR-only port, but something proper that works in both KKS_VR and official VR would be much better.

**Comment by ManlyMarco** [comment]
Resolved in #55 and https://github.com/lotsofbears/KK_SensibleH (both are needed)
