### ISSUE TITLE
Can I install KKS_VR in BetterRepack R10?

### ISSUE THREAD

**Issue by rossg4535** [IllusionMods/KKS_VR#29]
Hi, I just downloaded BetterRepack R10 and tried to install KKS_VR in for a full-support CharaStudio.

I've already downloaded, decompressed, and placed the following folders under the game directory.
BepInEx_x64_5.4.17.0
KKS_CharaStudioVR_0.0.2
KKS_VR_v1.2
KKSAPI_v1.36

And I created a CharaStudio shortcut, with command line changed as 
"D:\[ScrewThisNoise] Koikatsu Sunshine EX BetterRepack R10\CharaStudio.exe" --vr
But as I launched it, this shortcut just start the normal pc charastudio, even though I start it while launching the quest2 and steamvr.

Can anyone give me a guide or hint on fixing it? Really appreciated!

**Comment by ManlyMarco** [comment]
Do not use KKS_CharaStudioVR_0.0.2 and install latest versions of all mods required by KKS_VR by following their own installation instructions.

https://github.com/IllusionMods/KKS_VR#readme

BR should already have KKS_VR installed, you can start it through the game launcher. If not, you can use HF Patch to install it.
