### ISSUE TITLE
KKS POV; POV already implemented in KK_MainGameVR...

### ISSUE THREAD

**Issue by novalaunchersa** [IllusionMods/KKS_VR#45]
Since this guy already implemented POV in KK_MainGameVR I guess the process should be similar for KKS_VR? https://github.com/tony246642/KK_MainGameVR

**Comment by ManlyMarco** [comment]
Nice, it can be merged then, with an unknown amount of difficulty. Opened PRs for upstream #46 and the VR branch #47, both need to be merged in sequence. The first PR is going to be the main challenge I suspect.

**Comment by ManlyMarco** [comment]
Closed by #48
