### ISSUE TITLE
Null error using Vending machine

### ISSUE THREAD

**Issue by thojmr** [IllusionMods/KKS_VR#7]
Easy enough to reproduce, just walk up to a vending maching and use the interact button.  Doing so locks some of the UI buttons and you have to restart the game.

![null error](https://user-images.githubusercontent.com/72571672/151687319-7b620326-46ac-4b05-87c9-7bdcce0f7872.PNG)

**Comment by RodoxVR** [comment]
same

**Comment by ManlyMarco** [comment]
37bfb4700c5a2fe945be1c3d35180b0af934b140
